---
collections:
  - name: community.crypto
    version: 3.0.4
  - name: ansible.posix
    version: 2.1.0
roles:
  - name: geerlingguy.docker
    version: 7.6.0
  - name: geerlingguy.pip
    version: 3.1.0
