- name: Install gpg
  ansible.builtin.apt:
    name: gpg

- name: Add Docker apt key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: Add Docker apt repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
    filename: docker

- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
    install_recommends: false

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    append: true
    groups: docker

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
