- name: Create pihole directory
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/pihole"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
    mode: "755"

- name: Start/Update pihole container
  community.docker.docker_container:
    name: pihole
    image: "{{ pihole_image }}"
    pull: true
    restart_policy: unless-stopped
    env:
      TZ: "{{ timezone }}"
      FTLCONF_webserver_api_password: "{{ ftlconf_webserver_api_password }}"
      FTLCONF_dns_upstreams: "{{ ftlconf_dns_upstreams }}"
      FTLCONF_dns_listeningMode: 'SINGLE'
      FTLCONF_dns_interface: 'eth0' # To make it work across VLANs
    dns_servers:
      - 127.0.0.1
      - "{{ static_dns }}"
    network_mode: host
    volumes:
      - "/home/{{ ansible_user }}/pihole/pihole/:/etc/pihole/"
    log_driver: json-file
    log_options:
      max-size: "10m"
      max-file: "5"
    capabilities:
      - CAP_NET_BIND_SERVICE
      - CAP_SYS_NICE
      - CAP_CHOWN

- name: Check pihole container
  ansible.builtin.uri:
    url: http://localhost/admin
  register: result
  until: result.status == 200
  retries: 5
  delay: 10

- name: Remove old image versions
  community.docker.docker_prune:
    images: true
    images_filters:
      dangling: false

- name: Allow access to http port
  community.general.ufw:
    rule: allow
    port: "80"
    proto: tcp

- name: Allow access to https port
  community.general.ufw:
    rule: allow
    port: "443"
    proto: tcp

- name: Allow access to DNS port (TCP)
  community.general.ufw:
    rule: allow
    port: "53"
    proto: tcp

- name: Allow access to DNS port (UDP)
  community.general.ufw:
    rule: allow
    port: "53"
    proto: udp
